"""baseline existing schema

Revision ID: 20260724_0001
Revises:
Create Date: 2026-07-24 01:46:37.590554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260724_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('analyst_version', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_analyst_version'), 'analysis_reports', ['analyst_version'], unique=False)
    op.create_index(op.f('ix_analysis_reports_symbol'), 'analysis_reports', ['symbol'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('holdout_start', sa.DateTime(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_at'), 'heartbeats', ['at'], unique=False)
    op.create_table('holdout_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('killswitch_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('tripped', sa.Boolean(), nullable=False),
    sa.Column('tripped_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_killswitch_state_asset_class'), 'killswitch_state', ['asset_class'], unique=True)
    op.create_table('llm_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tool_calls_json', sa.Text(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('notional', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('fraction', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('hwm', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('pre_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_plan_id'), 'rules', ['plan_id'], unique=False)
    op.create_index(op.f('ix_rules_ticker'), 'rules', ['ticker'], unique=False)
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paper_only', sa.Boolean(), nullable=False),
    sa.Column('shadow', sa.Boolean(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('sized_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_plans_symbol'), 'trade_plans', ['symbol'], unique=False)
    op.create_table('backtest_metric_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_metric_rows_strategy'), 'backtest_metric_rows', ['strategy'], unique=False)
    op.create_index(op.f('ix_backtest_metric_rows_symbol'), 'backtest_metric_rows', ['symbol'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=64), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_broker_fill_id'), 'fills', ['broker_fill_id'], unique=True)
    op.create_index(op.f('ix_fills_filled_at'), 'fills', ['filled_at'], unique=False)
    op.create_index(op.f('ix_fills_ticker'), 'fills', ['ticker'], unique=False)
    op.create_table('graded_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('forward_return_pct', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('ttl_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('grade_after', sa.DateTime(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_calls_grade_after'), 'shadow_calls', ['grade_after'], unique=False)
    op.create_index(op.f('ix_shadow_calls_symbol'), 'shadow_calls', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_calls_symbol'), table_name='shadow_calls')
    op.drop_index(op.f('ix_shadow_calls_grade_after'), table_name='shadow_calls')
    op.drop_table('shadow_calls')
    op.drop_table('risk_events')
    op.drop_table('proposals')
    op.drop_table('graded_calls')
    op.drop_index(op.f('ix_fills_ticker'), table_name='fills')
    op.drop_index(op.f('ix_fills_filled_at'), table_name='fills')
    op.drop_index(op.f('ix_fills_broker_fill_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_backtest_metric_rows_symbol'), table_name='backtest_metric_rows')
    op.drop_index(op.f('ix_backtest_metric_rows_strategy'), table_name='backtest_metric_rows')
    op.drop_table('backtest_metric_rows')
    op.drop_index(op.f('ix_trade_plans_symbol'), table_name='trade_plans')
    op.drop_table('trade_plans')
    op.drop_index(op.f('ix_rules_ticker'), table_name='rules')
    op.drop_index(op.f('ix_rules_plan_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('llm_decisions')
    op.drop_index(op.f('ix_killswitch_state_asset_class'), table_name='killswitch_state')
    op.drop_table('killswitch_state')
    op.drop_table('holdout_access_log')
    op.drop_index(op.f('ix_heartbeats_at'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_analysis_reports_symbol'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_analyst_version'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
